# Generated by Django 2.1.7 on 2019-05-04 10:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('cer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cer_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('checkpoint_no', models.IntegerField(primary_key=True, serialize=False)),
                ('round_no', models.IntegerField()),
                ('lap_distant', models.FloatField()),
                ('place', models.CharField(max_length=50)),
                ('total_distant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('d_firstname', models.CharField(max_length=50)),
                ('d_lastname', models.CharField(max_length=50)),
                ('d_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('e_date', models.DateField()),
                ('e_locations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_firstname', models.CharField(max_length=50)),
                ('m_lastname', models.CharField(max_length=50)),
                ('m_phone', models.CharField(max_length=10)),
                ('m_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('eng_content', models.TextField()),
                ('thai_content', models.TextField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Event')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterInfo',
            fields=[
                ('regist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('pay_inSlip', models.CharField(max_length=255)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('bib', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
                ('runner_firstname', models.CharField(max_length=50)),
                ('runner_lastname', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Runner_Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('checkpoint_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CheckPoint')),
            ],
        ),
        migrations.CreateModel(
            name='RunningType',
            fields=[
                ('running_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('catergory', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Event')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SoloRunner',
            fields=[
                ('runner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Runner')),
                ('solo_runner_id', models.IntegerField()),
                ('bus', models.BooleanField()),
                ('resident', models.BooleanField()),
            ],
            bases=('backend.runner',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('runner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Runner')),
                ('team_id', models.IntegerField()),
                ('resident', models.BooleanField()),
            ],
            bases=('backend.runner',),
        ),
        migrations.AddField(
            model_name='runner_checkpoint',
            name='runner_bib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Runner'),
        ),
        migrations.AddField(
            model_name='runner',
            name='regist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.RegisterInfo'),
        ),
        migrations.AddField(
            model_name='registerinfo',
            name='running_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.RunningType'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='runner_bib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Runner'),
        ),
        migrations.AlterUniqueTogether(
            name='runner_checkpoint',
            unique_together={('runner_bib', 'checkpoint_no')},
        ),
        migrations.AddField(
            model_name='manager',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Team'),
        ),
        migrations.AddField(
            model_name='driver',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Team'),
        ),
    ]
