# Generated by Django 2.1.7 on 2019-05-06 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cer_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField()),
                ('lap_distant', models.FloatField()),
                ('place', models.CharField(max_length=50)),
                ('total_distant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_firstname', models.CharField(max_length=50)),
                ('d_lastname', models.CharField(max_length=50)),
                ('d_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('e_date', models.DateField()),
                ('e_locations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_firstname', models.CharField(max_length=50)),
                ('m_lastname', models.CharField(max_length=50)),
                ('m_phone', models.CharField(max_length=10)),
                ('m_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_content', models.TextField()),
                ('thai_content', models.TextField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Event')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('pay_inSlip', models.ImageField(upload_to='')),
                ('user_email', models.EmailField(max_length=254)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=3)),
                ('runner_firstname', models.CharField(max_length=50)),
                ('runner_lastname', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Runner_Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('checkpoint_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CheckPoint')),
            ],
        ),
        migrations.CreateModel(
            name='RunningType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catergory', models.CharField(choices=[('open junior', ' ประเภทจูเนียร์ทั่วไป อายุรวมกันไม่เกิน 280 ปี'), ('mixed junior', 'ประเภทจูเนียร์ผสม อายุรวมกันไม่เกิน 260 ปี'), ('open super junior', 'ประเภทซุปเปอร์จูเนียร์ทั่วไป อายุรวมกันตั้งแต่ 281 – 360'), ('mixed super junior', 'ประเภทซุปเปอร์จูเนียร์ผสม อายุรวมกันตั้งแต่ 261 – 340 ปี'), ('open senior ', 'ประเภทซีเนียร์ทั่วไป อายุรวมกันตั้งแต่ 361 – 440 ปี'), ('mixed senior ', 'ประเภทฃีเนียร์ผสม อายุรวมกันตั้งแต่ 341 – 420 ปี'), ('open super senior', 'ประเภทซูเปอร์ซีเนียร์ทั่วไป อายุรวมกันตั้งแต่ 441 ปีขึ้นไป'), ('mixed super senior ', 'ประเภทซูปซีเนียร์ผสม อายุรวมกันตั้งแต่ 421 ปีขึ้นไป'), ('open female', 'ประเภทหญิงทั่วไป ไม่จำกัดอายุ'), ('solo runner', 'ประเภทเดี่ยว ระยะ 120 km.')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SoloRunner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.BooleanField()),
                ('resident', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('runner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Runner')),
                ('team_name', models.CharField(max_length=100)),
                ('resident', models.BooleanField()),
                ('team_type', models.CharField(choices=[('team need runner', 'Team Need Runner'), ('runner need team', 'Runner Need Team')], max_length=50)),
            ],
            bases=('backend.runner',),
        ),
        migrations.AddField(
            model_name='solorunner',
            name='runner_bib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Runner'),
        ),
        migrations.AddField(
            model_name='runner_checkpoint',
            name='runner_bib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Runner'),
        ),
        migrations.AddField(
            model_name='runner',
            name='regist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.RegisterInfo'),
        ),
        migrations.AddField(
            model_name='registerinfo',
            name='running_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.RunningType'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='runner_bib',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Runner'),
        ),
        migrations.AlterUniqueTogether(
            name='runner_checkpoint',
            unique_together={('runner_bib', 'checkpoint_no')},
        ),
        migrations.AddField(
            model_name='runner',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.Team'),
        ),
        migrations.AddField(
            model_name='manager',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Team'),
        ),
        migrations.AddField(
            model_name='driver',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.Team'),
        ),
    ]
