# Generated by Django 2.1.7 on 2019-05-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cer_url',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='registerinfo',
            name='pay_inSlip',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
