# Generated by Django 2.1.7 on 2019-05-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerinfo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='registerinfo',
            name='user_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
