# Generated by Django 2.1.7 on 2019-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('team_need_runner', 'Team Need Runner'), ('runner_need_team', 'Runner Need Team')], default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runner',
            name='size',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=2),
        ),
    ]
