# Generated by Django 2.1.7 on 2019-05-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190506_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.Team'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='team_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='backend.Team'),
        ),
    ]
