# Generated by Django 2.1.7 on 2019-05-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190506_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerinfo',
            name='status',
            field=models.CharField(choices=[('Not paid', 'ยังไม่ได้ชำระเงิน'), ('Pending', 'รอการตรวจสอบ'), ('Already Paid', 'ชำระเงินแล้ว')], default='Not paid', max_length=100),
        ),
    ]
