# Generated by Django 2.1.7 on 2019-05-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_registerinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cer_url',
            field=models.ImageField(blank=True, null=True, upload_to='cetificate/'),
        ),
    ]
