# Generated by Django 2.1.7 on 2019-05-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190506_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
