# Generated by Django 2.1.7 on 2019-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_runner_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerinfo',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
