# Generated by Django 2.1.7 on 2019-05-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_runner_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerinfo',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
