# Generated by Django 2.1.7 on 2019-05-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190508_0234'),
        ('backend', '0006_auto_20190507_2021'),
    ]

    operations = [
    ]
