# Generated by Django 2.1.7 on 2019-05-15 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_merge_20190515_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='competition_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('checkpoint_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.CheckPoint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='registerinfo',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
